name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Установка Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      # Установка зависимостей Flutter
      - name: Установите зависимости
        run: flutter pub get

      # Проверка форматирования (опционально)
      # - name: Проверка форматирования
      #   run: flutter format --set-exit-if-changed .

      # Анализ кода
      - name: Анализ исходного кода
        run: flutter analyze

      # Запуск тестов
      - name: Запустите тесты
        run: flutter test
