name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Установка Flutter SDK конкретной версии
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0" # замени на актуальную стабильную

      - name: Установите зависимости
        run: flutter pub get

      - name: Анализ кода
        run: flutter analyze

      - name: Запустите тесты
        run: flutter test
